# -- Base Conf --
baseURL = "https://fossfa.ir/"
languageCode = "fa-IR"
title = "خانه"
theme = "bookworm-FE"
paginate = "7"

# - Post Url - 
[permalinks]
  # This section is only for working aliases properly

uglyurls = true

# ----- Plugins -----

# -- CSS Plugins --
[[params.plugins.css]]
link = "https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]] # Font Vazir
link ="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v29.1.0/dist/font-face.css"
[[params.plugins.css]] # Custom Css
link="plugins/customCss/main.css"
[[params.plugins.css]] # Vanilla Gallery
link="https://ghcdn.rawgit.org/Gnkalk/Vanilla-Gallery/main/Css-script/RO/Gallery-OCO.css"

# -- JS Plugins --
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Vazir"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

# ----- Theme Parameters -----
[params]

# -- SiteTitle --
SiteTitle = "فوسفا"

# -- Comment --
Commentrepo = "FOSSFA/Blog"
Commenttheme = "github-light"
Commentlabel = "Comment"

# -- Logo and Favicon --
logo = "images/logo.png"
logo_height = "50px"
favicon = "images/logo.png"

# -- Meta data --
description = "مکانی برای هواداران نرم افزار آزاد"

# -- contact form action --
contact_form_action = "#" # contact form works with https://formspree.io

# -- Search --
search = false

# -- Main Section --
mainSections = ["blog"]

# -- Footer --
copyright = "تمامی حقوق محفوظ است ، تحت لایسنس [FDL](http://www.gnu.org/licenses/fdl-1.3.html)"

# -- cookies --
[params.cookies]
enable = true
expire_days = 2

# -- Social --

# - telegram -
[[params.social]]
url = "https://t.me/FOSSFA"
icon = "lab la-telegram"

# - discord -
[[params.social]]
url = "https://discord.gg/5md25aNXyc"
icon = "lab la-discord"

# - Mastodon -
[[params.social]]
url = "https://fosstodon.org/@FOSSFarsi"
icon = "lab la-mastodon"

# - Matrix -
[[params.social]]
url = "https://matrix.to/#/#fossfa:matrix.org"
icon = "las la-comments"

# - Github -
[[params.social]]
url = "https://github.com/FOSSFA"
icon = "lab la-github"

# ----- Menu -----

# -- Main Menu --

[[menu.main]]
weight = 1
url = "/"
name = "خانه"
  
[[menu.main]]
weight = 3
url = "about"
name = "درباره ما"
  
[[menu.main]]
weight = 4
url = "contact"
name = "ارتباط با ما"

# -- Footer Menu --

[[menu.footer]]
weight = 1
url = "author/"
name = "نویسندگان"

[[menu.footer]]
weight = 2
url = "archive/"
name = "بایگانی"

# [[menu.footer]]
# weight = 3
# url = "privacy/"
# name = "امنیت و حریم خصوصی"
